apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: noop
spec:
  params:
    - name: BONFIRE_IMAGE
      type: string
      description: The container Bonfire image to use for the tekton tasks
      default: quay.io/redhat-user-workloads/hcc-devprod-tenant/hcc-cicd-tools/cicd-tools:eb1904eafc2d8af8a26b435de393d4776d9db2f6
  steps:
    - name: stub-images-script
      image: "$(params.BONFIRE_IMAGE)"
      # TODO - figure out how to include the script.
      script: |
        echo "I could do something, but not sure how, but you get the point :)"
