apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: python-benchmark-testing
spec:
  params:
    - name: BONFIRE_IMAGE
      type: string
      description: The container Bonfire image to use for the tekton tasks
      default: quay.io/redhat-services-prod/hcm-eng-prod-tenant/cicd-tools:a128bcd
    - name: PYTHON_TEST_IMAGE
      type: string
      description: The container used for running pytest test suite
      default: "registry.access.redhat.com/ubi8/python-311:1-91.1747189115" 
  steps:
    - name: python-benchmark-testing
      image: "$(params.PYTHON_TEST_IMAGE)"
      env:
        - name: OC_LOGIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.EPHEMERAL_ENV_PROVIDER_SECRET)
              key: token
        - name: OC_LOGIN_SERVER
          valueFrom:
            secretKeyRef:
              name: $(params.EPHEMERAL_ENV_PROVIDER_SECRET)
              key: url
        - name: BONFIRE_BOT
          value: "true"
      script: |
        #!/bin/bash
        set -ex

        echo "<-- write python benchmark testing -->"

