apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com:RedHatInsights/bonfire-tekton?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main" && files.all.exists(x, x.matches('.tekton/|pipelines/|tasks/'))
  labels:
    appstudio.openshift.io/application: bonfire-tekton
    appstudio.openshift.io/component: bonfire-tekton
  name: bonfire-tekton-on-pull-no-iqe-request
  namespace: rhtap-migration-tenant
spec:
  params:
  - name: URL
    value: '{{source_url}}'
  - name: REVISION
    value: '{{revision}}'
  - name: SNAPSHOT
    value: |
      {
        "application": "insights-ingress-go",
        "components": [
            {
                "name": "ingress",
                "containerImage": "quay.io/redhat-services-prod/hcc-integrations-tenant/insights-ingress-go:588f9ca32dbaf6ec6f52274b0d154555fb5fbc8b@sha256:5fa435277123e110533bc2ca98b4fe054de12166d830f2305de6b2d6a4f0150c",
                "source": {
                    "git": {
                        "url": "https://github.com/RedHatInsights/insights-ingress-go",
                        "revision": "1800069465e9f2cfe11983f7168eec1f5e749043"
                    }
                }
            }
        ],
        "artifacts": {}
      }
  - name: APP_NAME
    value: ingress
  - name: COMPONENT_NAME
    value: ingress
  - name: DEPLOY_TIMEOUT
    value: "950"
  pipelineRef:
      resolver: git
      params:
      - name: url
        value: '{{source_url}}'
      - name: revision
        value: '{{revision}}'
      - name: pathInRepo
        value: pipelines/basic_no_iqe.yaml
